### ISSUE TITLE
Improve error messaging

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader-ui-lib#47]
We should make it clearer why the upload has failed if something goes wrong, for example if they don't have enough WMATIC in their wallet.

From Ana's feedback: "When a user lacks sufficient WMATIC in their account, the upload process fails with a 500 error, but it doesn't provide any information about why it failed."

**Comment by jamiehewitt15** [comment]
I'm pretty sure that the DBS already send a message with each error message but if any error is missing an error message we can add that in on the backend.

**Comment by EnzoVezzaro** [comment]
this will be fixed in #52
