### ISSUE TITLE
Remove the "show code" option

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader-ui-lib#50]
It doesn't make sense to have this "show code" option on the UI that is used by consumers so we should remove it.

**Comment by AnaLoznianu** [comment]
Dependant on: https://github.com/oceanprotocol/uploader-ui-lib/issues/51. Once the component is moved on a standalone site, this should be closed as well

**Comment by EnzoVezzaro** [comment]
closing as it's already done
