### ISSUE TITLE
Check the WMATIC balance in the user's wallet before uploading

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader-ui-lib#52]
We should check the WMATIC balance in the user's wallet before uploading. It should prevent the user from clicking upload if they don't have enough WMATIC in their wallet.

**Comment by jamiehewitt15** [comment]
Note that when we implement https://github.com/oceanprotocol/uploader-ui-lib/issues/58 as planned we don't need to disable the button when a user doesn't have WMATIC - only when they don't have MATIC

**Comment by EnzoVezzaro** [comment]
fixed in #77
