### ISSUE TITLE
Importing the UI lib into Next.js app is not working 

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader-ui-lib#57]
I tried following the instructions in the readme and importing the UI-lib into a next.js app however it's giving me the error below. 

Instructions that I'm following from the readme:

```
import { DBSUploader } from '@oceanprotocol/dbs-ui-lib';
 
<DBSUploader 
   dbs_url={process.env.DBS_URL}
   dbs_account={process.env.DBS_ACCOUNT}
   infuraId={process.env.PUBLIC_INFURA_PROJECT_ID}
   walletConnectProjectId={process.env.PUBLIC_WALLETCONNECT_PROJECT_ID}
/>
```

The error that I'm getting:

```bash
Import trace for requested module:
./src/app/page.tsx
 ⨯ ./node_modules/@oceanprotocol/dbs-ui-lib/dist/index.cjs.js:1:93
Module not found: ESM packages (wagmi) need to be imported. Use 'import' to reference the package instead. https://nextjs.org/docs/messages/import-esm-externals

https://nextjs.org/docs/messages/module-not-found
```

**Comment by jamiehewitt15** [comment]
There are a lot of very old dependencies in the repo that could be contributing to this issue

**Comment by EnzoVezzaro** [comment]
did you take a look at [this repo](https://github.com/oceanprotocol/demo-dbs-ui)? this is a nextjs app with dbs ui on it.

**Comment by jamiehewitt15** [comment]
Yeah, that demo app works. The difference is that you've installed all of the dependencies for the uploader-ui-lib in that repo. The dependencies should be packaged up with the uploader-ui-lib so that the user only needs to run `npm i uploader-ui-lib` and then import the component as it says in the readme.

**Comment by EnzoVezzaro** [comment]
i updated the dependencies and bundled them into the distribution, now it's not necessary to install any package besides uploader to use the component into a nextjs app. 

Said that, when importing this component on a SSR app, you need to take into consideration this guide I created [here](https://github.com/oceanprotocol/uploader-ui-lib#nextjs-setup-for-ocean-protocol-uploader-ui-library).

**Comment by AnaLoznianu** [comment]
@EnzoVezzaro can we close this?

**Comment by EnzoVezzaro** [comment]
yes, we can close it 👍🏽
