### ISSUE TITLE
UI should accept payments in MATIC rather than just wrapped matic

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader-ui-lib#58]
If the user doesn't have sufficient wrapped Matic in their wallet, the first transaction should be to wrap their matic and then proceed with the upload.

**Comment by AnaLoznianu** [comment]
What's an estimation for this?

**Comment by AnaLoznianu** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/S1---DApps-63f8b8c26e838c0017f34d23/issues/oceanprotocol/uploader-ui-lib/58?planning-poker) with Zenhub @jamiehewitt15
