### ISSUE TITLE
The wrong currency is displayed

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader-ui-lib#62]
The payment is in WMATIC but is quoted in the front end as MATIC

**Comment by jamiehewitt15** [comment]
This should be closed in: https://github.com/oceanprotocol/uploader_arweave/issues/57

**Comment by EnzoVezzaro** [comment]
this seems done in https://api.test.uploader.oceanprotocol.com/ and https://api.uploader.oceanprotocol.com/

We can close this issue.
