### ISSUE TITLE
Setup new subdomain

### ISSUE THREAD

**Issue by jamiehewitt15** [oceanprotocol/uploader-ui-lib#68]
I'm guessing that we'll probably go with uploader.oceanprotocol.com but we can also discuss other options

**Comment by mihaisc** [comment]
sold, will do when the time is right :D

**Comment by md00ux** [comment]
backend endpoints:
- test: https://api.test.uploader.oceanprotocol.com/
- prod: https://api.uploader.oceanprotocol.com/

**Comment by mihaisc** [comment]
will we have a test deployment and a prod deployment on the frontend?
