### ISSUE TITLE
Network selector is misleading

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/uploader-ui-lib#91]
Why do we have a network selector if I cannot change anything?  

<img width="345" alt="Screenshot 2023-10-17 at 18 22 01" src="https://github.com/oceanprotocol/uploader-ui-lib/assets/84312885/5e2b1999-e304-4d2a-8a7f-c0833f82c24f">

**Comment by EnzoVezzaro** [comment]
because it was develop to handle multiple networks and multiple currency. Right now we only have 1 network and 1 currency, but if you run the app in dev mode, you see 2 networks (polygon and mumbai). And other services might required different networks than those.

**Comment by jamiehewitt15** [comment]
We will need the token selector when the filecoin microservice is launched.

**Comment by EnzoVezzaro** [comment]
do we need to discuss further this or can be closed?

**Comment by AnaLoznianu** [comment]
Thanks for giving all the details. Closing it
